### ISSUE TITLE
Ошибка при Автозапуске

### ISSUE THREAD

**Issue by gimtonic** [afiskon/postgresql-initd#1]
Добрый вечер!
Собирал postgres из исходников. Понадобилась очень автозапуск)
Скопировал этот скрипт в /etc/init.d/postgresql и правим несколько первых строк:
PGUSER,PGLOG,prefix -оставил без изменения.
PGDATA у меня такая /usr/local/pgsql/data 

Во время ввода команды sudo update-rc.d postgresql defaults
Появляются такие ошибки!!!
insserv: warning: script 'K03postgresql' missing LSB tags and overrides
insserv: warning: script 'postgresql' missing LSB tags and overrides

ubuntu-16.04
Качал отсюда https://ftp.postgresql.org/pub/source/v9.6.6/postgresql-9.6.6.tar.gz

Автозагрузка работает. Меня просто смутило предупреждение!
Как бы от него избавится?)

**Comment by afiskon** [comment]
Привет. Вот тут https://raspberrypi.stackexchange.com/a/13361 подсказывают что в 16.04 нужно дописать в начало скрипта тэгов по аналогии с /etc/init.d/skeleton Если у вас получится, пришлите пожалуйста pull request!

**Comment by gimtonic** [comment]
Да. Я находил это тоже) Хорошо. Пришлю PR
